/** page.tsx를 감싸는 파일 페이지 밖에 적용하고 싶은 것들을 넣는 곳 */

import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="navbar">
            <Link href="/">홈</Link>
            <Link href="/list">List</Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
